config/routes.rb
Memo::Application.routes.draw do
  resources :memolists do
  resources :comments
  end

  match  'hello' => 'memolist#hello'
  match  'bye'   => 'memolist#bye'
  match  'getdata'   => 'memolist#getdata'
  match  'makedb'   => 'memolist#makedb'
  match  'dblist'   => 'memolist#dblist'
  match  'dbdelete'   => 'memolist#dbdelete'

  root :to => 'memolist#hello'

end

app/controllers/memolist_controller.rb
# -*- coding: utf-8 -*-
class MemolistController < ApplicationController

#before_filter :authenticate

  def hello
  end

  def dblist
    @memodb = Memodb.all(:order => "created_at DESC")
  end

  def dbdelete
    name = params[:name]
    Memodb.delete_all("name='"+name+"'")
    render :action => 'hello'
  end

  def getdata
	  require 'hpricot'
      require 'open-uri' 

      #名前、ページ数取得
      @name = params[:name][:name]
      @number = params[:number].to_i
      if @name !~ /[0-9A-Za-z]+$/ then
        render :action => 'error'  and return
      end
      unless @name.blank?
      #スペースをプラスに置換
      @name = @name.gsub(/(\s)/,"+")
      #Hpricot
      doc = Hpricot(open("http://www.xvideos.com/?k=#{@name}&p=#{@number}")) 
      tmp =  (doc/"div.thumb"/:a).map {|href| href[:href]}
      @img = (doc/"img").map {|img| img[:src]}
      @img.delete("http://img100.xvideos.com/videos/thumbs/xvideos.gif")
      #ページ数取得
      page = (doc/"div.pagination"/:a).map {|href| href[:href]}
      @page = page.length/2
      i=0
       @result = Array.new();
        #url取得
        tmp.each do |tmp|
        @result[i] = tmp[6,7]
        if @result[i][@result[i].length-1] == "/" then
           @result[i] = tmp[6,6]
        end
        i+=1
        end
        render :action => 'confirm'  
        else
        render :action => 'error'
        end
    end

    def rescue_action_in_public(exception)
        case exception
           when ActiveRecord::RecordNotFound, ::ActionController::UnknownAction, ::ActionController::RoutingError, ActionView::TemplateError, NoMethodError
          render :action => 'error'
          end
    end

    def makedb
      name = params[:name]
      url  = params[:url]
      memodb = Memodb.new
      memodb.name = name
      memodb.url = url
      memodb.save
          render :action => 'hello'  
    end

end

app/controllers/memolists_controller.rb
# -*- coding: utf-8 -*-
class MemolistsController < ApplicationController

#before_filter :authenticate

  def index
    @memodb = Memodb.all(:order => "created_at DESC")
  end

  def destroy
    name = params[:name]
    Memodb.delete_all("name='"+name+"'")
    #render :action => 'hello'
    render json: { memodb: @memodb }
  end

  def show
      @memodb = Memodb.all(:order => "created_at DESC")
  end
    
  def getdata
	  require 'hpricot'
      require 'open-uri' 

      #名前、ページ数取得
      @name = params[:name][:name]
      @number = params[:number].to_i
      if @name !~ /[0-9A-Za-z]+$/ then
        render :action => 'error'  and return
      end
      unless @name.blank?
      #スペースをプラスに置換
      @name = @name.gsub(/(\s)/,"+")
      #Hpricot
      doc = Hpricot(open("http://www.xvideos.com/?k=#{@name}&p=#{@number}&sort=rating")) 
      tmp = (doc/"a.miniature").map {|href| href[:href]}
      @img = (doc/"img").map {|img| img[:src]}
      @img.delete("http://img100.xvideos.com/videos/thumbs/xvideos.gif")
      #ページ数取得
      page = (doc/"div#pag"/:a).map {|href| href[:href]}
      @page = page.length/2
      i=0
       @result = Array.new();
        #url取得
        tmp.each do |tmp|
        tmp2 = tmp[28,7]
        if tmp2[tmp2.length-1] == "/" then
           tmp2 = tmp[28,6]
        end
        @result[i] = "http://www.xvideos.com/sitevideos/flv_player_site_v4.swf?id_video=#{tmp2}"
        i+=1
        end
        render :action => 'confirm'  
        else
        render :action => 'error'
        end
    end

    def rescue_action_in_public(exception)
        case exception
           when ActiveRecord::RecordNotFound, ::ActionController::UnknownAction, ::ActionController::RoutingError, ActionView::TemplateError, NoMethodError
          render :action => 'error'
          end
    end

    def create
      name = params[:name]
      url  = params[:url]
      memodb = Memodb.new
      memodb.name = name
      memodb.url = url
      memodb.save
          render :action => 'hello'  
    end

end

app/helpers/memolist_helper.rb
module MemolistHelper
end

app/views/memolists/bye.html.erb
<script type="text/javascript">
//<![CDATA[
$(function(){
	var hsort_flg = false;

	//setup
	var vg = $("#grid-content").vgrid({
		easeing: "easeOutQuint",
		time: 400,
		delay: 20,
		fadeIn: {
			time: 500,
			delay: 50
		},
		onStart: function(){
			$("#message1")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		},
		onFinish: function(){
			$("#message2")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		}
	});

	//sort
	$("#hsort").click(function(e){
		hsort_flg = !hsort_flg;
		$("#grid-content").vgsort(function(a, b){
			var _a = $(a).find('h3').text();
			var _b = $(b).find('h3').text();
			var _c = hsort_flg ? 1 : -1 ;
			return (_a > _b) ? _c * -1 : _c ;
		}, "easeInOutExpo", 300, 0);
		return false;
	});
	$("#rsort").click(function(e){
		$("#grid-content").vgsort(function(a, b){
			return Math.random() > 0.5 ? 1 : -1 ;
		}, "easeInOutExpo", 300, 20);
		hsort_flg = true;
		return false;
	});
});
//]]>
</script>

<input type="button" id="hsort" value="Headline Sort" />
<input type="button" id="rsort" value="Random Sort" />
<br>
	<div id="grid-content">
	  <li>
		<% @href.each do |href| %>
		<a href="#">
		  <img src="http://dka-hero.com/<%= href %>" alt="" align="right">
		</a>
		<% end %>
	  </li>
  </div>

app/views/memolists/confirm.html.erb
<%= stylesheet_link_tag    "mystyle" %>
<script type="text/javascript">
//<![CDATA[
$(function(){
	var hsort_flg = false;

	//setup
	var vg = $("#grid-content").vgrid({
		easeing: "easeOutQuint",
		time: 400,
		delay: 20,
		fadeIn: {
			time: 500,
			delay: 50
		},
		onStart: function(){
			$("#message1")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		},
		onFinish: function(){
			$("#message2")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		}
	});

	//sort
	$("#rsort").click(function(e){
		$("#grid-content").vgsort(function(a, b){
			return Math.random() > 0.5 ? 1 : -1 ;
		}, "easeInOutExpo", 300, 20);
		hsort_flg = true;
		return false;
	});
});
//]]>
</script>

<%# shadowbox %>
<script type="text/javascript">
function sbxload( el ) {
}
function sbxchange( el ) {
}
Shadowbox.init(
{
	counterLimit:20,
	overlayColor:'#000000',
	overlayOpacity:0.6,
	onFinish : sbxload,
	onChange: sbxchange
},
function () {
	Shadowbox.setup("a.swf", {
		gallery: "swf",
        width: 510,
        height: 400,
        player: "swf",
        continuous: true,
		counterType:"skip",
        flashParams: { allowScriptAccess: "always" }
	});
});
</script>

<%# SORT %>
  <form action="#" method="get" style="margin-bottom:10px;">
	<input type="button" id="rsort" value="Random Sort" />
	<span id="message1">onStart</span>
	<span id="message2">onFinish</span>
  </form>
  <div id="grid-content">
<%# imgの個数繰り返す %>
		<% i = 0
		   while i < @img.size %>
<%# target 少し大きく %>
		   <div id="target">
		   <img src="<%= @img[i] %>" width="360" height="300">
		     <div style="display:inline;position: absolute; top:0px; left:0px;">
		   <a class="swf" href="<%= @result[i] %>">
		   	<img src="<%= asset_path "click.png" %>"  width="360" height="300" ></a>
<Div Align="right">
		   <%=link_to "保存★",:action=>"makedb",:name=>@img[i],:url => @result[i] %>	
</Div>
      </div>
           </div>	
<% i += 1
   end %>
</div>
<%# ページ数 %>
<br>
	<center>
	  
      <div class="pagination">
        <ul>
		  <% i = 0
			 while i < @page-1 %>
			 <li> 
			   <%=link_to i+1,:action=>"getdata",:number=>i,:name => {:"name" => @name} %>	
		  <% i += 1 %>
</li>
<% end %>
</ul>
</div>
	<p><a href="javascript:location.href='/hello'">トップページにもどる</a>
	&nbsp;
</p>
</center>

app/views/memolists/dblist.html.erb
 <style type="text/css">
 /*<![CDATA[*/
body {
	padding: 10px;
	margin: 0;
}
#message1 {
	display: inline-block;
	width: 6em;
	text-align: center;
	background: green;
	visibility: hidden;
	color: #FFFFFF;
}
#message2 {
	display: inline-block;
	width: 6em;
	text-align: center;
	background: red;
	visibility: hidden;
	color: #FFFFFF;
}
#grid-content {
	margin: 0 60px;   
	overflow: hidden;
	border: 0.5px solid #eb6100;
}
#target {
    width: 370px;
    height: 325px;
}/*]]>*/
</style>

<script type="text/javascript">
//<![CDATA[
$(function(){
	var hsort_flg = false;

	//setup
	var vg = $("#grid-content").vgrid({
		easeing: "easeOutQuint",
		time: 400,
		delay: 20,
		fadeIn: {
			time: 500,
			delay: 50
		},
		onStart: function(){
			$("#message1")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		},
		onFinish: function(){
			$("#message2")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		}
	});

	//sort
	$("#rsort").click(function(e){
		$("#grid-content").vgsort(function(a, b){
			return Math.random() > 0.5 ? 1 : -1 ;
		}, "easeInOutExpo", 300, 20);
		hsort_flg = true;
		return false;
	});
});
//]]>
</script>

<script type="text/javascript">
function sbxload( el ) {
}
function sbxchange( el ) {
}
Shadowbox.init(
{
	counterLimit:20,
	overlayColor:'#000000',
	overlayOpacity:0.6,
	onFinish : sbxload,
	onChange: sbxchange
},
function () {
	Shadowbox.setup("a.swf", {
		gallery: "swf",
        width: 510,
        height: 400,
        player: "swf",
        continuous: true,
		counterType:"skip",
        flashParams: { allowScriptAccess: "always" }
	});
});
</script>
  <form action="#" method="get" style="margin-bottom:10px;">
	<input type="button" id="rsort" value="Random Sort" />
	<span id="message1">onStart</span>
	<span id="message2">onFinish</span>
  </form>
<div id="grid-content">
  <% @memodb.each do |memodb| %>
   <div id="memodb_<%= memodb.id %>">
	<div id="target">
	  <img src="<%= memodb.name %>" width="360" height="300">
	  <div style="display:inline;position: absolute; top:0px; left:0px;">
		<a class="swf" href="<%= memodb.url %>">
		<img src="<%= asset_path "click.png" %>"  width="360" height="300" ></a>
	  <div Align="right">
		<%=link_to "DELETE",:action=>"dbdelete",:name=> memodb.name%></div>
	</div>	
  </div>
  </div>
  <% end %>
</div>
<br>
	<center>
	<br>
	<a href="javascript:location.href='/hello'">トップページにもどる</a>
	</center>

<script>
$(function() {
  setTimeout(function() {
    $('#notice').fadeOut("slow");
  }, 800);
  
  $('a[data-method="delete"]').live('ajax:success', function(e, data, status, xhr) {
    $('#memodb_'+data.memodb.id).fadeOut("slow");
  }
  
});
</script>

app/views/memolists/error.html.erb
 <style type="text/css">
body
    {
     margin:0px;          /* ページ全体のmargin */
     padding:0px;         /* ページ全体のpadding */
     text-align:center;   /* 下記のautoに未対応用のセンタリング */
    }

#site-box
    {
	width: 600px;
	height: 250px;
    margin: -150px 0px 0px -300px;
	left: 50%;
	top: 50%;
	position: absolute;
    }
 </style>
 <div id=site-box>
<div class="alert alert-error fade in "><a class="close" data-dismiss="alert">×</a> <br>エラー!<br><br>1.何も入力されていない<br>2.日本語が入力されている<br></div>
<br><br>
<p><a href="#" onClick="history.back(); return false;">前のページにもどる</a></p>
</div>

app/views/memolists/index.html.erb
 <style type="text/css">
body
    {
     margin:0px;          /* ページ全体のmargin */
     padding:0px;         /* ページ全体のpadding */
     text-align:center;   /* 下記のautoに未対応用のセンタリング */
    }

#site-box
    {
	width: 600px;
	height: 250px;
    margin: -150px 0px 0px -300px;
	left: 50%;
	top: 50%;
	position: absolute;
    }
 </style>
<div id="site-box">
<%= form_tag({:action=>"getdata"}, {"number"=>"0"}) %>
<%= text_field 'name','name' %>
<br><br>
<%= submit_tag "送信",:class=>"btn-success"%>
</div>

app/views/memolists/show.html.erb
 <style type="text/css">
 /*<![CDATA[*/
body {
	padding: 10px;
	margin: 0;
}
#message1 {
	display: inline-block;
	width: 6em;
	text-align: center;
	background: green;
	visibility: hidden;
	color: #FFFFFF;
}
#message2 {
	display: inline-block;
	width: 6em;
	text-align: center;
	background: red;
	visibility: hidden;
	color: #FFFFFF;
}
#grid-content {
	margin: 0 60px;   
	overflow: hidden;
	border: 0.5px solid #eb6100;
}
#target {
    width: 370px;
    height: 325px;
}/*]]>*/
</style>

<script type="text/javascript">
//<![CDATA[
$(function(){
	var hsort_flg = false;

	//setup
	var vg = $("#grid-content").vgrid({
		easeing: "easeOutQuint",
		time: 400,
		delay: 20,
		fadeIn: {
			time: 500,
			delay: 50
		},
		onStart: function(){
			$("#message1")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		},
		onFinish: function(){
			$("#message2")
				.css("visibility", "visible")
				.fadeOut("slow",function(){
					$(this).show().css("visibility", "hidden");
				});
		}
	});

	//sort
	$("#rsort").click(function(e){
		$("#grid-content").vgsort(function(a, b){
			return Math.random() > 0.5 ? 1 : -1 ;
		}, "easeInOutExpo", 300, 20);
		hsort_flg = true;
		return false;
	});
});
//]]>
</script>

<script type="text/javascript">
function sbxload( el ) {
}
function sbxchange( el ) {
}
Shadowbox.init(
{
	counterLimit:20,
	overlayColor:'#000000',
	overlayOpacity:0.6,
	onFinish : sbxload,
	onChange: sbxchange
},
function () {
	Shadowbox.setup("a.swf", {
		gallery: "swf",
        width: 510,
        height: 400,
        player: "swf",
        continuous: true,
		counterType:"skip",
        flashParams: { allowScriptAccess: "always" }
	});
});
</script>
  <form action="#" method="get" style="margin-bottom:10px;">
	<input type="button" id="rsort" value="Random Sort" />
	<span id="message1">onStart</span>
	<span id="message2">onFinish</span>
  </form>
<div id="grid-content">
  <% @memodb.each do |memodb| %>
	<div id="target">
	  <img src="<%= memodb.name %>" width="360" height="300">
	  <div style="display:inline;position: absolute; top:0px; left:0px;">
		<a class="swf" href="<%= memodb.url %>">
		<img src="<%= asset_path "click.png" %>"  width="360" height="300" ></a>
	  <div Align="right">
		<%=link_to "DELETE",:action=>"destroy",:name=> memodb.name%></div>
<%= link_to "Delete",memolists_path,:confirm => 'Sure?',
                            :method => :delete,:remote => true%>	</div>	
  </div>
  <% end %>
</div>
<br>
	<center>
	<br>
	<a href="javascript:location.href='/hello'">トップページにもどる</a>
	</center>

<script>
$(function() {
  setTimeout(function() {
    $('#notice').fadeOut("slow");
  }, 800);
  
  $('a[data-method="delete"]').live('ajax:success', function(e, data, status, xhr) {
    $('#memolist_'+data.memolist.id).fadeOut("slow");
  });
  
});
</script>